baankproject/baankproject/baankapp/urls.py
from django.urls import path
from . import views

app_name = 'baankapp'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('success_page/', views.success_page, name='success_page'),
    path('newpage/', views.newpage, name='newpage'),
    # path('showpage/', views.showpage, name='showpage'),

]

baankproject/baankproject/baankproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('baankapp.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baankproject/baankproject/baankapp/models.py
from django.db import models


class Material(models.Model):
    name = models.CharField(max_length=50, default=False)

    def __str__(self):
        return self.name


class Customer(models.Model):
    name = models.CharField(max_length=100)
    DOB = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=5, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=False)
    phone_number = models.CharField(max_length=15)
    mail_id = models.EmailField()
    address = models.TextField()
    account_type = models.CharField(max_length=20,
                                    choices=[('Savings', 'Savings Account'), ('Current', 'Current Account')],
                                    default=False)

    def __str__(self):
        return self.name

baankproject/baankproject/baankapp/forms.py
from django import forms
from .models import Customer, Material


class CustomerDetailsForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name', 'DOB', 'age', 'gender', 'phone_number', 'mail_id', 'address', 'account_type']

baankproject/baankproject/baankapp/views.py
from django.contrib import auth, messages

from django.contrib.auth.models import User
from django.shortcuts import render, redirect

from django.contrib import messages

from baankapp.forms import CustomerDetailsForm


def home(request):
    return render(request, 'home.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('baankapp:newpage')
        else:
            messages.error(request, 'Invalid credentials')

    return render(request, 'login.html')


def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if not username:
            messages.error(request, 'Username cannot be empty.')
            return redirect('baankapp:register')

        if password != confirm_password:
            messages.error(request, 'Passwords do not match.')
            return redirect('baankapp:register')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Username is already taken')
            return redirect('baankapp:register')

        user = User.objects.create_user(username=username, password=password)

        if user:

            auth.login(request, user)
            # messages.success(request, 'Registration successful')
            return redirect('baankapp:login')
        else:
            messages.error(request, 'Error creating user')

    return render(request, 'register.html')


def newpage(request):
    if request.method == 'POST':
        form = CustomerDetailsForm(request.POST)
        if form.is_valid():
            # customer = form.save(commit=True)
            # customer.materials_provided.set(form.cleaned_data['materials_provided'])
            # customer.save()
            form.save()

            return redirect('baankapp:success_page')
    else:
        form = CustomerDetailsForm()

    return render(request, 'newpage.html', {'form': form})


def success_page(request):
    return render(request, 'success_page.html')

baankproject/baankproject/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <title>Home Page</title>
</head>
<body>

  <header>
    <nav>
      <ul>

        <li><a href="{% url 'baankapp:login' %}">Login</a></li>
        <li><a href="{% url 'baankapp:register' %}">Register</a></li>
        <li class="dropdown">
          <a href="">Branches</a>
          <ul class="dropdown-content">
              <a href="https://en.wikipedia.org/wiki/Alappuzha_district">Alapuzha</a><br>
              <a href="https://en.wikipedia.org/wiki/Ernakulam_district">Ernakulam</a><br>
              <a href="https://en.wikipedia.org/wiki/Kollam_district">Kollam</a><br>
              <a href="https://en.wikipedia.org/wiki/Kozhikode_district">Kozhicode</a><br>
              <a href="https://en.wikipedia.org/wiki/Thiruvananthapuram_district">Thiruvananthapuram</a><br>
          </ul>
        </li>
      </ul>
    </nav>
  </header>

  <main>
    <button onclick="showLoginForm()">Click Here</button>
  </main>

  <script>
    function showLoginForm() {
      window.location.href = "{% url 'baankapp:login' %}";
    }
  </script>

</body>
</html>

baankproject/baankproject/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Login Page</title>
</head>
<body>

<form method="post" action="{% url 'baankapp:login' %}">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" id="username" name="username"><br>

    <label for="password">Password</label>
    <input type="password" id="password" name="password"><br>

    <input type="submit" value="Submit">
    <a href="{% url 'baankapp:register' %}">Register</a>

</form>

</body>
</html>

baankproject/baankproject/templates/newpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>New Page</title>
</head>
<body>
{% if messages %}
    <div class="messages">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}

  <button id="showFormBtn"> Form</button>

  <div id="formContainer" style="display: none;">
      <h2>Customer Details</h2>
    <form method="post" action="{% url 'baankapp:newpage' %}">
      {% csrf_token %}
      {{ form.as_p }}
                <label for="district">District:</label>
  <select id="district" onchange="updateBranchOptions()">
    <option value="ernakulam">Ernakulam</option>
    <option value="thiruvananthapuram">Thiruvananthapuram</option>

  </select>

  <br>

  <label for="branch">Branch:</label>
  <select id="branch">

  </select>

  <script>
    function updateBranchOptions() {
      var districtSelect = document.getElementById('district');
      var branchSelect = document.getElementById('branch');
      var selectedDistrict = districtSelect.value;


      branchSelect.innerHTML = '';


      if (selectedDistrict === 'ernakulam') {
        addOption(branchSelect, 'aluva', 'Aluva');
        addOption(branchSelect, 'vytila', 'Vytila');
        addOption(branchSelect, 'edapally', 'Edapally');
        addOption(branchSelect, 'kalamasherry', 'kalamasherry');
      } else if (selectedDistrict === 'thiruvananthapuram') {
        addOption(branchSelect, 'nemom', 'Nemom');
        addOption(branchSelect, 'veli', 'Veli');
        addOption(branchSelect, 'kochuveli', 'Kochuveli');
        addOption(branchSelect, 'kovalam', 'Kovalam');

      }


      // You can also fetch the branch options dynamically using AJAX if needed
    }

    function addOption(selectElement, value, text) {
      var option = document.createElement('option');
      option.value = value;
      option.text = text;
      selectElement.add(option);
    }

    // Initialize branch options based on the default district selection
    updateBranchOptions();
  </script>
        <div class="form-check">
            <p>Materials provided:</p>
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">
            Credit card
           </label>
        </div>
       <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
            <label class="form-check-label" for="flexCheckChecked">
            Debit card
            </label>
       </div>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked">
            <label class="form-check-label" for="flexCheckChecked">
            Check Book
            </label>
       </div>




      <input type="submit" value="Submit">
      <a href="{% url 'baankapp:home' %}">Logout</a>
    </form>


  </div>

  <script>
    document.getElementById('showFormBtn').addEventListener('click', function () {
      document.getElementById('formContainer').style.display = 'block';
    });
  </script>

</body>
</html>

baankproject/baankproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Register Page</title>
</head>
<body>

<form method="post" action="{% url 'baankapp:register' %}">
    {% csrf_token %}
    <label for="username">Username</label>
    <input type="text" id="username" name="username"><br>

    <label for="password">Password</label>
    <input type="password" id="password" name="password"><br>

    <label for="confirm_password">Confirm Password</label>
    <input type="password" id="confirm_password" name="confirm_password"><br>

    <input type="submit" value="Submit">
    <a href="{% url 'baankapp:login' %}">Login</a>
</form>

</body>
</html>

baankproject/baankproject/templates/success_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Success Page</title>
</head>
<body>
    <h2>Application Accepted</h2>
    <!-- Display customer details or any other information you want -->
    <a href="{% url 'baankapp:home' %}">Return to Home Page</a>
</body>
</html>